/* The following code was generated by JFlex 1.4 on 12/30/16 7:44 PM */

package AST;

import beaver.Symbol;
import beaver.Scanner;
import AST.phpParser.Terminals;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4
 * on 12/30/16 7:44 PM from the specification file
 * <tt>C:/Users/vishnu/Documents/GitHub/SQL-injection-detection/spec/php.flex</tt>
 */
public final class phpScanner extends Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\54\1\16"+
    "\1\0\1\6\3\0\1\21\1\22\1\5\1\20\1\17\1\55\1\24"+
    "\1\4\12\10\1\0\1\41\1\11\1\23\1\15\1\12\1\0\16\7"+
    "\1\45\1\44\2\7\1\46\1\47\6\7\1\60\1\0\1\61\1\0"+
    "\1\43\1\0\1\36\1\7\1\42\1\53\1\30\1\31\1\7\1\14"+
    "\1\26\2\7\1\27\1\50\1\37\1\40\1\13\1\52\1\34\1\32"+
    "\1\33\1\35\1\7\1\25\1\7\1\51\1\7\1\56\1\0\1\57"+
    "\54\0\1\7\12\0\1\7\4\0\1\7\5\0\27\7\1\0\37\7"+
    "\1\0\u01ca\7\4\0\14\7\16\0\5\7\7\0\1\7\1\0\1\7"+
    "\201\0\5\7\1\0\2\7\2\0\4\7\10\0\1\7\1\0\3\7"+
    "\1\0\1\7\1\0\24\7\1\0\123\7\1\0\213\7\10\0\236\7"+
    "\11\0\46\7\2\0\1\7\7\0\47\7\110\0\33\7\5\0\3\7"+
    "\55\0\53\7\25\0\12\10\4\0\2\7\1\0\143\7\1\0\1\7"+
    "\17\0\2\7\7\0\2\7\12\10\3\7\2\0\1\7\20\0\1\7"+
    "\1\0\36\7\35\0\131\7\13\0\1\7\16\0\12\10\41\7\11\0"+
    "\2\7\4\0\1\7\5\0\26\7\4\0\1\7\11\0\1\7\3\0"+
    "\1\7\27\0\31\7\107\0\1\7\1\0\13\7\127\0\66\7\3\0"+
    "\1\7\22\0\1\7\7\0\12\7\4\0\12\10\1\0\7\7\1\0"+
    "\7\7\5\0\10\7\2\0\2\7\2\0\26\7\1\0\7\7\1\0"+
    "\1\7\3\0\4\7\3\0\1\7\20\0\1\7\15\0\2\7\1\0"+
    "\3\7\4\0\12\10\2\7\23\0\6\7\4\0\2\7\2\0\26\7"+
    "\1\0\7\7\1\0\2\7\1\0\2\7\1\0\2\7\37\0\4\7"+
    "\1\0\1\7\7\0\12\10\2\0\3\7\20\0\11\7\1\0\3\7"+
    "\1\0\26\7\1\0\7\7\1\0\2\7\1\0\5\7\3\0\1\7"+
    "\22\0\1\7\17\0\2\7\4\0\12\10\25\0\10\7\2\0\2\7"+
    "\2\0\26\7\1\0\7\7\1\0\2\7\1\0\5\7\3\0\1\7"+
    "\36\0\2\7\1\0\3\7\4\0\12\10\1\0\1\7\21\0\1\7"+
    "\1\0\6\7\3\0\3\7\1\0\4\7\3\0\2\7\1\0\1\7"+
    "\1\0\2\7\3\0\2\7\3\0\3\7\3\0\14\7\26\0\1\7"+
    "\25\0\12\10\25\0\10\7\1\0\3\7\1\0\27\7\1\0\12\7"+
    "\1\0\5\7\3\0\1\7\32\0\2\7\6\0\2\7\4\0\12\10"+
    "\25\0\10\7\1\0\3\7\1\0\27\7\1\0\12\7\1\0\5\7"+
    "\3\0\1\7\40\0\1\7\1\0\2\7\4\0\12\10\1\0\2\7"+
    "\22\0\10\7\1\0\3\7\1\0\51\7\2\0\1\7\20\0\1\7"+
    "\21\0\2\7\4\0\12\10\12\0\6\7\5\0\22\7\3\0\30\7"+
    "\1\0\11\7\1\0\1\7\2\0\7\7\72\0\60\7\1\0\2\7"+
    "\14\0\7\7\11\0\12\10\47\0\2\7\1\0\1\7\2\0\2\7"+
    "\1\0\1\7\2\0\1\7\6\0\4\7\1\0\7\7\1\0\3\7"+
    "\1\0\1\7\1\0\1\7\2\0\2\7\1\0\4\7\1\0\2\7"+
    "\11\0\1\7\2\0\5\7\1\0\1\7\11\0\12\10\2\0\4\7"+
    "\40\0\1\7\37\0\12\10\26\0\10\7\1\0\44\7\33\0\5\7"+
    "\163\0\53\7\24\0\1\7\12\10\6\0\6\7\4\0\4\7\3\0"+
    "\1\7\3\0\2\7\7\0\3\7\4\0\15\7\14\0\1\7\1\0"+
    "\12\10\6\0\46\7\1\0\1\7\5\0\1\7\2\0\53\7\1\0"+
    "\u014d\7\1\0\4\7\2\0\7\7\1\0\1\7\1\0\4\7\2\0"+
    "\51\7\1\0\4\7\2\0\41\7\1\0\4\7\2\0\7\7\1\0"+
    "\1\7\1\0\4\7\2\0\17\7\1\0\71\7\1\0\4\7\2\0"+
    "\103\7\45\0\20\7\20\0\125\7\14\0\u026c\7\2\0\21\7\1\0"+
    "\32\7\5\0\113\7\25\0\15\7\1\0\4\7\16\0\22\7\16\0"+
    "\22\7\16\0\15\7\1\0\3\7\17\0\64\7\43\0\1\7\4\0"+
    "\1\7\3\0\12\10\46\0\12\10\6\0\130\7\10\0\51\7\1\0"+
    "\1\7\5\0\106\7\12\0\35\7\51\0\12\10\36\7\2\0\5\7"+
    "\13\0\54\7\25\0\7\7\10\0\12\10\46\0\27\7\11\0\65\7"+
    "\53\0\12\10\6\0\12\10\15\0\1\7\135\0\57\7\21\0\7\7"+
    "\4\0\12\10\51\0\36\7\15\0\2\7\12\10\54\7\32\0\44\7"+
    "\34\0\12\10\3\0\3\7\12\10\44\7\153\0\4\7\1\0\4\7"+
    "\3\0\2\7\11\0\300\7\100\0\u0116\7\2\0\6\7\2\0\46\7"+
    "\2\0\6\7\2\0\10\7\1\0\1\7\1\0\1\7\1\0\1\7"+
    "\1\0\37\7\2\0\65\7\1\0\7\7\1\0\1\7\3\0\3\7"+
    "\1\0\7\7\3\0\4\7\2\0\6\7\4\0\15\7\5\0\3\7"+
    "\1\0\7\7\164\0\1\7\15\0\1\7\20\0\15\7\145\0\1\7"+
    "\4\0\1\7\2\0\12\7\1\0\1\7\3\0\5\7\6\0\1\7"+
    "\1\0\1\7\1\0\1\7\1\0\4\7\1\0\13\7\2\0\4\7"+
    "\5\0\5\7\4\0\1\7\64\0\2\7\u0a7b\0\57\7\1\0\57\7"+
    "\1\0\205\7\6\0\4\7\3\0\2\7\14\0\46\7\1\0\1\7"+
    "\5\0\1\7\2\0\70\7\7\0\1\7\20\0\27\7\11\0\7\7"+
    "\1\0\7\7\1\0\7\7\1\0\7\7\1\0\7\7\1\0\7\7"+
    "\1\0\7\7\1\0\7\7\120\0\1\7\u01d5\0\2\7\52\0\5\7"+
    "\5\0\2\7\4\0\126\7\6\0\3\7\1\0\132\7\1\0\4\7"+
    "\5\0\51\7\3\0\136\7\21\0\33\7\65\0\20\7\u0200\0\u19b6\7"+
    "\112\0\u51cd\7\63\0\u048d\7\103\0\56\7\2\0\u010d\7\3\0\20\7"+
    "\12\10\2\7\24\0\57\7\20\0\31\7\10\0\106\7\61\0\11\7"+
    "\2\0\147\7\2\0\4\7\1\0\4\7\14\0\13\7\115\0\12\7"+
    "\1\0\3\7\1\0\4\7\1\0\27\7\35\0\64\7\16\0\62\7"+
    "\34\0\12\10\30\0\6\7\3\0\1\7\4\0\12\10\34\7\12\0"+
    "\27\7\31\0\35\7\7\0\57\7\34\0\1\7\12\10\46\0\51\7"+
    "\27\0\3\7\1\0\10\7\4\0\12\10\6\0\27\7\3\0\1\7"+
    "\5\0\60\7\1\0\1\7\3\0\2\7\2\0\5\7\2\0\1\7"+
    "\1\0\1\7\30\0\3\7\2\0\13\7\7\0\3\7\14\0\6\7"+
    "\2\0\6\7\2\0\6\7\11\0\7\7\1\0\7\7\221\0\43\7"+
    "\15\0\12\10\6\0\u2ba4\7\14\0\27\7\4\0\61\7\u2104\0\u016e\7"+
    "\2\0\152\7\46\0\7\7\14\0\5\7\5\0\1\7\1\0\12\7"+
    "\1\0\15\7\1\0\5\7\1\0\1\7\1\0\2\7\1\0\2\7"+
    "\1\0\154\7\41\0\u016b\7\22\0\100\7\2\0\66\7\50\0\14\7"+
    "\164\0\5\7\1\0\207\7\23\0\12\10\7\0\32\7\6\0\32\7"+
    "\13\0\131\7\3\0\6\7\2\0\6\7\2\0\6\7\2\0\3\7"+
    "\43\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\1\1\1\4\1\5\1\6"+
    "\1\1\1\6\1\1\1\7\1\10\1\11\1\12\1\13"+
    "\11\4\1\14\1\4\1\1\1\15\1\16\1\17\1\1"+
    "\1\2\1\0\1\20\2\0\1\6\1\21\2\0\1\22"+
    "\1\23\1\4\1\24\7\4\1\25\1\4\1\26\5\0"+
    "\6\4\1\27\1\30\1\4\4\0\1\4\1\31\1\32"+
    "\1\4\1\33\2\4\1\0\1\34\1\0\1\35\1\36"+
    "\2\4\1\37\1\0\2\4\1\40\1\41\12\0\1\42"+
    "\2\0\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\62\0\226\0\62\0\310\0\372"+
    "\0\u012c\0\u015e\0\u0190\0\u01c2\0\u01f4\0\62\0\62\0\62"+
    "\0\62\0\u01c2\0\u0226\0\u0258\0\u028a\0\u02bc\0\u02ee\0\u0320"+
    "\0\u0352\0\u0384\0\u03b6\0\62\0\u03e8\0\u01c2\0\62\0\62"+
    "\0\62\0\u041a\0\u044c\0\u047e\0\u04b0\0\u04e2\0\u0514\0\62"+
    "\0\62\0\u0546\0\u0578\0\62\0\62\0\u05aa\0\372\0\u05dc"+
    "\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708\0\372\0\u073a"+
    "\0\62\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898"+
    "\0\u08ca\0\u08fc\0\u092e\0\u0960\0\372\0\372\0\u0992\0\u09c4"+
    "\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\372\0\372\0\u0abe\0\372"+
    "\0\u0af0\0\u0b22\0\u0b54\0\62\0\u0b86\0\372\0\372\0\u0bb8"+
    "\0\u0bea\0\62\0\u0c1c\0\u0c4e\0\u0c80\0\62\0\372\0\u0cb2"+
    "\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\u0dde\0\u0e10\0\u0e42"+
    "\0\u0e74\0\62\0\u0ea6\0\u0ed8\0\62";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\2\10\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\2\1\23\1\24\1\10\1\25\1\26"+
    "\1\10\1\27\1\30\1\10\1\31\1\32\1\33\1\34"+
    "\1\10\1\2\4\10\1\35\3\10\1\36\1\37\1\40"+
    "\1\41\1\42\1\2\64\0\1\4\63\0\1\43\1\44"+
    "\63\0\1\45\3\0\2\45\10\0\14\45\1\0\1\45"+
    "\1\46\10\45\15\0\2\10\2\0\2\10\10\0\14\10"+
    "\1\0\1\10\1\0\10\10\16\0\1\11\63\0\1\47"+
    "\10\0\1\50\53\0\1\51\67\0\1\50\37\0\3\52"+
    "\1\0\1\52\1\0\1\53\1\52\2\0\2\53\1\0"+
    "\1\54\5\52\1\0\14\53\1\0\1\53\1\0\10\53"+
    "\5\0\1\55\7\0\2\10\2\0\1\10\1\56\10\0"+
    "\14\10\1\0\1\10\1\0\10\10\15\0\2\10\2\0"+
    "\2\10\10\0\4\10\1\57\7\10\1\0\1\10\1\0"+
    "\10\10\15\0\2\10\2\0\2\10\10\0\2\10\1\60"+
    "\11\10\1\0\1\61\1\0\10\10\15\0\2\10\2\0"+
    "\2\10\10\0\11\10\1\62\2\10\1\0\1\10\1\0"+
    "\10\10\15\0\2\10\2\0\2\10\10\0\7\10\1\63"+
    "\4\10\1\0\1\10\1\0\10\10\15\0\2\10\2\0"+
    "\2\10\10\0\3\10\1\64\10\10\1\0\1\10\1\0"+
    "\10\10\15\0\2\10\2\0\2\10\10\0\12\10\1\65"+
    "\1\10\1\0\1\10\1\0\10\10\15\0\2\10\2\0"+
    "\2\10\10\0\13\10\1\66\1\0\1\10\1\0\10\10"+
    "\15\0\2\10\2\0\2\10\10\0\7\10\1\67\4\10"+
    "\1\0\1\10\1\0\10\10\15\0\2\10\2\0\2\10"+
    "\10\0\14\10\1\0\1\10\1\0\5\10\1\70\2\10"+
    "\24\0\1\71\43\0\1\43\1\3\1\4\57\43\5\72"+
    "\1\73\54\72\7\0\2\45\2\0\2\45\10\0\14\45"+
    "\1\0\1\45\1\0\10\45\52\0\1\74\30\0\1\75"+
    "\47\0\3\52\1\0\1\52\1\0\2\52\2\0\2\52"+
    "\1\0\1\54\5\52\1\0\14\52\1\0\1\52\1\0"+
    "\10\52\7\0\3\52\1\0\1\52\1\0\2\53\2\0"+
    "\2\53\1\0\1\54\5\52\1\76\14\53\1\0\1\53"+
    "\1\0\10\53\15\0\2\10\2\0\2\10\10\0\1\10"+
    "\1\77\12\10\1\0\1\10\1\0\10\10\15\0\2\10"+
    "\2\0\2\10\10\0\5\10\1\100\6\10\1\0\1\10"+
    "\1\0\10\10\15\0\2\10\2\0\1\10\1\101\10\0"+
    "\14\10\1\0\1\10\1\0\10\10\15\0\2\10\2\0"+
    "\2\10\10\0\2\10\1\102\11\10\1\0\1\10\1\0"+
    "\10\10\15\0\2\10\2\0\2\10\10\0\10\10\1\103"+
    "\3\10\1\0\1\10\1\0\10\10\15\0\2\10\2\0"+
    "\2\10\10\0\14\10\1\0\1\10\1\0\6\10\1\104"+
    "\1\10\15\0\2\10\2\0\2\10\10\0\14\10\1\0"+
    "\1\10\1\0\7\10\1\105\15\0\2\10\2\0\2\10"+
    "\10\0\6\10\1\106\5\10\1\0\1\10\1\0\10\10"+
    "\15\0\2\10\2\0\2\10\10\0\5\10\1\107\6\10"+
    "\1\0\1\10\1\0\10\10\6\0\5\72\1\110\54\72"+
    "\4\0\1\4\1\73\121\0\1\111\30\0\1\112\60\0"+
    "\1\113\55\0\2\10\2\0\2\10\10\0\2\10\1\114"+
    "\11\10\1\0\1\10\1\0\10\10\15\0\2\10\2\0"+
    "\2\10\10\0\3\10\1\115\10\10\1\0\1\10\1\0"+
    "\10\10\15\0\2\10\2\0\2\10\10\0\13\10\1\116"+
    "\1\0\1\10\1\0\10\10\15\0\2\10\2\0\2\10"+
    "\10\0\5\10\1\117\6\10\1\0\1\10\1\0\10\10"+
    "\15\0\2\10\2\0\2\10\10\0\3\10\1\120\10\10"+
    "\1\0\1\10\1\0\10\10\15\0\2\10\2\0\2\10"+
    "\10\0\10\10\1\121\3\10\1\0\1\10\1\0\10\10"+
    "\15\0\2\10\2\0\2\10\10\0\14\10\1\0\1\10"+
    "\1\0\6\10\1\122\1\10\6\0\4\72\1\4\1\110"+
    "\54\72\46\0\1\123\26\0\1\124\62\0\1\125\54\0"+
    "\2\10\2\0\2\10\10\0\3\10\1\126\10\10\1\0"+
    "\1\10\1\0\10\10\15\0\2\10\2\0\2\10\10\0"+
    "\3\10\1\127\10\10\1\0\1\10\1\0\10\10\15\0"+
    "\2\10\2\0\2\10\10\0\1\10\1\130\12\10\1\0"+
    "\1\10\1\0\10\10\15\0\2\10\2\0\2\10\10\0"+
    "\2\10\1\131\11\10\1\0\1\10\1\0\10\10\55\0"+
    "\1\132\25\0\1\133\55\0\2\10\2\0\2\10\10\0"+
    "\7\10\1\134\4\10\1\0\1\10\1\0\10\10\15\0"+
    "\2\10\2\0\2\10\10\0\1\10\1\135\12\10\1\0"+
    "\1\10\1\0\10\10\24\0\1\136\52\0\2\10\2\0"+
    "\2\10\10\0\3\10\1\137\10\10\1\0\1\10\1\0"+
    "\10\10\15\0\2\10\2\0\2\10\10\0\14\10\1\0"+
    "\1\10\1\140\10\10\45\0\1\141\12\0\1\142\44\0"+
    "\1\143\61\0\1\144\74\0\1\145\41\0\1\146\74\0"+
    "\1\147\52\0\1\150\61\0\1\151\76\0\1\152\50\0"+
    "\1\153\46\0\1\154\66\0\1\155\27\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3850];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\7\1\4\11"+
    "\12\1\1\11\2\1\3\11\2\1\1\0\1\1\2\0"+
    "\2\11\2\0\2\11\13\1\1\11\5\0\11\1\4\0"+
    "\7\1\1\0\1\11\1\0\4\1\1\11\1\0\2\1"+
    "\1\11\1\1\12\0\1\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  private Symbol sym(short id) {
    return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), yytext());
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public phpScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public phpScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1722) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { return sym(Terminals.OPMUL);
          }
        case 36: break;
        case 2: 
          { /* discard token */
          }
        case 37: break;
        case 13: 
          { return sym(Terminals.OPMINUS);
          }
        case 38: break;
        case 34: 
          { return sym(Terminals.SQL);
          }
        case 39: break;
        case 23: 
          { return sym(Terminals.AND);
          }
        case 40: break;
        case 8: 
          { return sym(Terminals.OPPLUS);
          }
        case 41: break;
        case 24: 
          { return sym(Terminals.NOT);
          }
        case 42: break;
        case 16: 
          { return sym(Terminals.IDENTIFIER);
          }
        case 43: break;
        case 32: 
          { return sym(Terminals.FILEVAR);
          }
        case 44: break;
        case 18: 
          { return sym(Terminals.STRVAR);
          }
        case 45: break;
        case 31: 
          { return sym(Terminals.POST);
          }
        case 46: break;
        case 35: 
          { return sym(Terminals.SQLNUMROWS);
          }
        case 47: break;
        case 1: 
          { throw new RuntimeException("Illegal character \""+yytext()+ "\" at line "+yyline+", column "+yycolumn);
          }
        case 48: break;
        case 9: 
          { return sym(Terminals.LPAREN);
          }
        case 49: break;
        case 29: 
          { return sym(Terminals.WHILE);
          }
        case 50: break;
        case 19: 
          { return sym(Terminals.RSBRACE);
          }
        case 51: break;
        case 33: 
          { return sym(Terminals.REQUIRE);
          }
        case 52: break;
        case 17: 
          { return sym(Terminals.PHPEND);
          }
        case 53: break;
        case 7: 
          { return sym(Terminals.SEP);
          }
        case 54: break;
        case 21: 
          { return sym(Terminals.OR);
          }
        case 55: break;
        case 15: 
          { return sym(Terminals.RBRACE);
          }
        case 56: break;
        case 28: 
          { return sym(Terminals.PHPBEGIN);
          }
        case 57: break;
        case 11: 
          { return sym(Terminals.ASSIGN);
          }
        case 58: break;
        case 27: 
          { return sym(Terminals.TRUE);
          }
        case 59: break;
        case 25: 
          { return sym(Terminals.ELSE);
          }
        case 60: break;
        case 4: 
          { return sym(Terminals.READIDENTIFIER);
          }
        case 61: break;
        case 10: 
          { return sym(Terminals.RPAREN);
          }
        case 62: break;
        case 5: 
          { return sym(Terminals.NUMBER);
          }
        case 63: break;
        case 30: 
          { return sym(Terminals.FALSE);
          }
        case 64: break;
        case 12: 
          { return sym(Terminals.SEMICOLON);
          }
        case 65: break;
        case 22: 
          { return sym(Terminals.LSBRACE);
          }
        case 66: break;
        case 20: 
          { return sym(Terminals.IF);
          }
        case 67: break;
        case 6: 
          { return sym(Terminals.OPRELATIONAL);
          }
        case 68: break;
        case 26: 
          { return sym(Terminals.ECHO);
          }
        case 69: break;
        case 14: 
          { return sym(Terminals.LBRACE);
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { return sym(Terminals.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
